# Strings, Lists, Arrays, and Dictionaries

## Strings 

#### Strings are lists of characters. Any character you can type from a computer keyboard, plus various other characters, can be elements in a string. 

In [1]:
a = "My cat's name is"
b = "Poncho"

In [2]:
c = a + " " + b 
c

"My cat's name is Poncho"

In [3]:
# Operator overloading

f = "Susie"
3 * f

'SusieSusieSusie'

In [5]:
f + f + f

'SusieSusieSusie'


### Unicode Characters

#### To accommodate the much larger number of symbols needed to encode the world’s languages, the International Standards Orga- nization (ISO) developed the Unicode standard, which Python uses, specifi- cally UTF-8, which you may see referenced from time to time

In [8]:
ord('a')

97

In [9]:
chr(945)

'α'

In [10]:
ord('α')

945

In [11]:
ord('ф')

1092

In [12]:
chr(1092)

'ф'

In [13]:
ord('й')

1081

### List

#### Python has two data structures, lists and tuples, that consist of a list of one or more elements. 

In [21]:
a = [0, 1, 1, 2, 3, 5, 8, 13]

In [22]:
b = [5., "girl", 2+0j, "horse", 21]

In [23]:
b[0]

5.0

In [24]:
b[1]

'girl'

In [25]:
b[-1]

21

In [26]:
b[-2]

'horse'

#### Individual elements of lists can be changed

In [27]:
b

[5.0, 'girl', (2+0j), 'horse', 21]

In [28]:
b[0] = b[0] + 2

In [29]:
b

[7.0, 'girl', (2+0j), 'horse', 21]

In [30]:
b[3] = 3.14159

In [31]:
b

[7.0, 'girl', (2+0j), 3.14159, 21]

In [32]:
b[1] = b[1] + "s & boys"

In [33]:
b

[7.0, 'girls & boys', (2+0j), 3.14159, 21]

In [35]:
a + a

[0, 1, 1, 2, 3, 5, 8, 13, 0, 1, 1, 2, 3, 5, 8, 13]

In [36]:
# Adding lists concatenates them
a + b

[0, 1, 1, 2, 3, 5, 8, 13, 7.0, 'girls & boys', (2+0j), 3.14159, 21]

#### Slicing lists

In [39]:
b[1:4]

['girls & boys', (2+0j), 3.14159]

In [40]:
b

[7.0, 'girls & boys', (2+0j), 3.14159, 21]

In [41]:
b[1:4]

['girls & boys', (2+0j), 3.14159]

In [42]:
b[3:5]

[3.14159, 21]

In [44]:
b[3:len(b)]

[3.14159, 21]

In [45]:
b[2:]

[(2+0j), 3.14159, 21]

In [46]:
b[:3]

[7.0, 'girls & boys', (2+0j)]

In [47]:
b[:]

[7.0, 'girls & boys', (2+0j), 3.14159, 21]

In [48]:
b

[7.0, 'girls & boys', (2+0j), 3.14159, 21]

In [49]:
b[1:-1]

['girls & boys', (2+0j), 3.14159]

In [51]:
len(b)

5

In [52]:
b

[7.0, 'girls & boys', (2+0j), 3.14159, 21]

In [53]:
b[0::2]

[7.0, (2+0j), 21]

In [54]:
b[0::1]

[7.0, 'girls & boys', (2+0j), 3.14159, 21]

In [55]:
b[0::3]

[7.0, 3.14159]

In [56]:
b[1::3]

['girls & boys', 21]

In [57]:
b[1::2]

['girls & boys', 3.14159]

In [58]:
b[1::3]

['girls & boys', 21]

In [59]:
b[2::3]

[(2+0j)]

#### Multidimensional Lists

In [60]:
a = [[3, 9], [8, 5], [11, 1]]

In [61]:
a

[[3, 9], [8, 5], [11, 1]]

In [62]:
a[0]

[3, 9]

In [63]:
a[1]

[8, 5]

In [64]:
a[1][0]

8

In [65]:
a[2][1]

1

#### Appending Lists

In [66]:
g = [9, 7, 5]

In [67]:
id(g)

5081499968

In [68]:
g = g + [1, 2, 3]

In [69]:
g

[9, 7, 5, 1, 2, 3]

In [70]:
id(g)

5081419584

In [71]:
g += [4, 5, 6]

In [72]:
g

[9, 7, 5, 1, 2, 3, 4, 5, 6]

In [73]:
id(g)

5081419584

In [74]:
g

[9, 7, 5, 1, 2, 3, 4, 5, 6]

In [75]:
g.append(11)

In [76]:
g

[9, 7, 5, 1, 2, 3, 4, 5, 6, 11]

In [77]:
id(g)

5081419584

#### We say that g has been changed in place, that is, without changing its id or memory location. By the way, the *= operator also makes changes in place.

In [78]:
g.append([13, 14, 15])

In [80]:
g  # The append method added the list [13, 14, 15] to g

[9, 7, 5, 1, 2, 3, 4, 5, 6, 11, [13, 14, 15]]

#### Tuples

In [81]:
c = (1, 1, 2, 3, 5, 8, 13)

In [82]:
c[4]

5

In [83]:
c[4] = 7

TypeError: 'tuple' object does not support item assignment

In [84]:
(3, 4, 5) + (2, 4, 6)

(3, 4, 5, 2, 4, 6)

In [85]:
(7, 8, 9) * 3

(7, 8, 9, 7, 8, 9, 7, 8, 9)

In [86]:
d = [3, 4, 5]

In [89]:
d + [2]

[3, 4, 5, 2]

#### Note: While lists of length 1 are written as [a], tuples are written as (a,). The comma is needed to tell Python that this is a tuple of length 1 and not a simple variable.

In [91]:
(8, 9, 10, 11) + (1, )

(8, 9, 10, 11, 1)

#### Dictionaries

In [92]:
room = {"Yujin": 309, "Jake": 582, "Ja'Marr": 764}

In [93]:
room

{'Yujin': 309, 'Jake': 582, "Ja'Marr": 764}

In [95]:
room["Yujin"]

309

In [1]:
weird = {"tank": 52, 846: "horse", 'bones': [23, 'fox', 'grass'], 'phrase': 'I am here'}

In [2]:
weird

{'tank': 52,
 846: 'horse',
 'bones': [23, 'fox', 'grass'],
 'phrase': 'I am here'}

In [3]:
weird[846]

'horse'

In [4]:
weird['bones']

[23, 'fox', 'grass']

In [5]:
weird['phrase']

'I am here'

#### you can build up and add to dictionaries in a straightforward manner

In [7]:
d = {}

In [8]:
d["last name"] = "Alberts"

In [9]:
d

{'last name': 'Alberts'}

In [10]:
d["first name"] = "Marie"

In [12]:
d["birthday"] = "January 27"

In [13]:
d

{'last name': 'Alberts', 'first name': 'Marie', 'birthday': 'January 27'}

In [14]:
d.keys()

dict_keys(['last name', 'first name', 'birthday'])

In [15]:
d.values()

dict_values(['Alberts', 'Marie', 'January 27'])

In [16]:
type(d.keys())

dict_keys

In [20]:
d.keys()

dict_keys(['last name', 'first name', 'birthday'])

In [21]:
for i in d.keys():
    print(i)

last name
first name
birthday


#### You can also create a dictionary from a list of tuple pairs.

In [24]:
g = [("Melissa", "Canada"), ("Jeana", "China"), ("Etienne", "France")]

In [25]:
gd = dict(g)

In [26]:
gd

{'Melissa': 'Canada', 'Jeana': 'China', 'Etienne': 'France'}

In [27]:
gd["Jeana"]

'China'

In [28]:
gd.keys()

dict_keys(['Melissa', 'Jeana', 'Etienne'])

In [29]:
gd.values()

dict_values(['Canada', 'China', 'France'])

#### Numpy Arrays

##### The NumPy array is the real workhorse of data structures for scientific and en- gineering applications. The NumPy array is similar to a list but where all the elements are the same type. The NumPy array constitutes a new type, namely ndarray.

In [30]:
a = [0, 0, 1, 4, 7, 16, 31, 64, 127]

In [32]:
import numpy as np

b = np.array(a)
b

array([  0,   0,   1,   4,   7,  16,  31,  64, 127])

In [33]:
c = np.array([1, 4., -2, 7])

In [34]:
c

array([ 1.,  4., -2.,  7.])

##### The second way arrays can be created is with the NumPy linspace or logspace functions. 

In [35]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
%precision 1

'%.1f'

In [37]:
np.logspace(1, 3, 5)

array([  10. ,   31.6,  100. ,  316.2, 1000. ])

In [38]:
np.linspace(1, 3, 5)

array([1. , 1.5, 2. , 2.5, 3. ])

##### A third way arrays can be created is using the NumPy arange function. The form of the function is a range(start, stop, step)

In [41]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [43]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(0, 1, 0.3)

array([0. , 0.3, 0.6, 0.9])

##### A fourth way to create an array is with the zeros and ones functions. As their names imply, they create arrays where all the elements are either zeros or ones.

In [45]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [46]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [47]:
np.ones(8, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1])

#### Mathematical Operations with Arrays

In [48]:
a = np.linspace(-1., 5, 7)

In [49]:
a

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [50]:
a*6

array([-6.,  0.,  6., 12., 18., 24., 30.])

In [51]:
a/5

array([-0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [52]:
a**3

array([ -1.,   0.,   1.,   8.,  27.,  64., 125.])

In [53]:
a+4

array([3., 4., 5., 6., 7., 8., 9.])

In [54]:
(a+3)*2

array([ 4.,  6.,  8., 10., 12., 14., 16.])

In [55]:
np.sin(a)

array([-0.8,  0. ,  0.8,  0.9,  0.1, -0.8, -1. ])

In [56]:
np.set_printoptions(precision=4)

In [57]:
np.sin(a)

array([-0.8415,  0.    ,  0.8415,  0.9093,  0.1411, -0.7568, -0.9589])

In [58]:
np.exp(-a)

array([2.7183, 1.    , 0.3679, 0.1353, 0.0498, 0.0183, 0.0067])

In [60]:
1. + np.exp(a)

array([  1.3679,   2.    ,   3.7183,   8.3891,  21.0855,  55.5982,
       149.4132])

In [61]:
b = 5*np.ones(8)

In [65]:
b

array([9., 9., 9., 9., 9., 9., 9., 9.])

In [63]:
b += 4

In [66]:
b

array([9., 9., 9., 9., 9., 9., 9., 9.])

In [67]:
x = np.linspace(-3.14, 3.14, 21)

In [68]:
x

array([-3.14 , -2.826, -2.512, -2.198, -1.884, -1.57 , -1.256, -0.942,
       -0.628, -0.314,  0.   ,  0.314,  0.628,  0.942,  1.256,  1.57 ,
        1.884,  2.198,  2.512,  2.826,  3.14 ])

In [69]:
y = np.cos(x)
y

array([-1.0000e+00, -9.5061e-01, -8.0827e-01, -5.8688e-01, -3.0811e-01,
        7.9633e-04,  3.0962e-01,  5.8817e-01,  8.0920e-01,  9.5111e-01,
        1.0000e+00,  9.5111e-01,  8.0920e-01,  5.8817e-01,  3.0962e-01,
        7.9633e-04, -3.0811e-01, -5.8688e-01, -8.0827e-01, -9.5061e-01,
       -1.0000e+00])

In [70]:
a

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [71]:
np.log(a)

/var/folders/78/hgt6ztdn5bvbxpk7fmt5jlfc0000gn/T/ipykernel_932/176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)
/var/folders/78/hgt6ztdn5bvbxpk7fmt5jlfc0000gn/T/ipykernel_932/176755284.py:1: RuntimeWarning: invalid value encountered in log
  np.log(a)


array([   nan,   -inf, 0.    , 0.6931, 1.0986, 1.3863, 1.6094])

In [78]:
a = np.array([34., -12, 5.])
a

array([ 34., -12.,   5.])

In [79]:
b = np.array([68., 5.0, 20.])
b

array([68.,  5., 20.])

In [80]:
a+b

array([102.,  -7.,  25.])

In [81]:
a-b

array([-34., -17., -15.])

In [82]:
a*b

array([2312.,  -60.,  100.])

In [84]:
a / b  # These operations with arrays are called vectorized operations 

array([ 0.5 , -2.4 ,  0.25])

#### Slicing and Addressing Arrays

In [85]:
y = np.array([0., 1.3, 5., 10.9, 18.9, 28.7, 40.])
t = np.array([0., 0.49, 1., 1.5, 2.08, 2.55, 3.2])

##### You can find the average velocity for time interval i using the formula
\begin{equation}
\frac{y_{i}-y_{i-1}}{t_{i}-t_{i-1}}
\end{equation}

In [86]:
y[:-1]

array([ 0. ,  1.3,  5. , 10.9, 18.9, 28.7])

In [87]:
y[1:]

array([ 1.3,  5. , 10.9, 18.9, 28.7, 40. ])

In [88]:
y[1:]-y[:-1]

array([ 1.3,  3.7,  5.9,  8. ,  9.8, 11.3])

In [90]:
v = (y[1:]-y[:-1])/(t[1:]-t[:-1])
v

array([ 2.6531,  7.2549, 11.8   , 13.7931, 20.8511, 17.3846])

In [92]:
tv = (t[1:]-t[:-1])/2
tv

array([0.245, 0.255, 0.25 , 0.29 , 0.235, 0.325])

#### Fancy Indexing: Boolean Indexing

In [93]:
b = 1.0 / np.arange(0.2, 3, 0.2)
b

array([5.    , 2.5   , 1.6667, 1.25  , 1.    , 0.8333, 0.7143, 0.625 ,
       0.5556, 0.5   , 0.4545, 0.4167, 0.3846, 0.3571])

In [94]:
b[b > 1]  # Boolean indexing

array([5.    , 2.5   , 1.6667, 1.25  ])

In [95]:
b[b > 1] = 1  # You can reassign all the elements of b that are greater than 1 to have a value of 1 with the following assignment:

In [96]:
b

array([1.    , 1.    , 1.    , 1.    , 1.    , 0.8333, 0.7143, 0.625 ,
       0.5556, 0.5   , 0.4545, 0.4167, 0.3846, 0.3571])

In [97]:
b.size

14

In [98]:
c = np.linspace(0, 10, b.size)
c

array([ 0.    ,  0.7692,  1.5385,  2.3077,  3.0769,  3.8462,  4.6154,
        5.3846,  6.1538,  6.9231,  7.6923,  8.4615,  9.2308, 10.    ])

In [101]:
c[b == 1] = 3  # A Boolean condition on one array can be used to index a different array if the two arrays have the same size, as in the above example.

In [102]:
c

array([ 3.    ,  3.    ,  3.    ,  3.    ,  3.    ,  3.8462,  4.6154,
        5.3846,  6.1538,  6.9231,  7.6923,  8.4615,  9.2308, 10.    ])

In [103]:
y = np.sin(np.linspace(0, 4*np.pi, 9))
y

array([ 0.0000e+00,  1.0000e+00,  1.2246e-16, -1.0000e+00, -2.4493e-16,
        1.0000e+00,  3.6739e-16, -1.0000e+00, -4.8986e-16])

In [104]:
y[np.abs(y) < 1.e-15] = 0

In [105]:
y

array([ 0.,  1.,  0., -1.,  0.,  1.,  0., -1.,  0.])

#### Multidimensional Arrays and Matrices


In [106]:
b = np.array([[1., 4, 5], [9, 7, 4]])
b

array([[1., 4., 5.],
       [9., 7., 4.]])

In [107]:
a = np.ones(4, 3, dtype=float)
a

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.