## Section 5 

In [6]:
distance = input("Input trip distance (miles): ")
distance

Input trip distance (miles):  250


'250'

In [7]:
distance = eval(distance)
distance

250

In [8]:
distance = input("Input trip distance (miles): ")
distance

Input trip distance (miles):  250


'250'

In [9]:
distance = float(distance)
distance

250.0

In [6]:
""" Calculates time , electrical energy used , and cost of electricity
for a trip in an electric vehicle"""
distance = float(input("Input trip distance (miles): "))

mpk = 3.9  # [miles/kilowatt -h] car mileage
speed = 60.  # [miles/h] average speed
cost_per_kWh = 0.22  # [$/kW-h] price of electricity
time = distance / speed  # [hours]
energy = distance / mpk  # [kW-h]
cost = energy * cost_per_kWh  # [$]

print("\nDuration of trip = {0:0.1f} hours".format(time))  # Formatting
print("Electricity used = {0:0.1f} kW-h (@ {1:0.2f} miles/kW-h)".format(energy, mpk))
print("Cost of electricity = ${0:0.2f} (@ ${1:0.2f}/kW-h)".format(cost, cost_per_kWh))

Input trip distance (miles):  250



Duration of trip = 4.2 hours
Electricity used = 64.1 kW-h (@ 3.90 miles/kW-h)
Cost of electricity = $14.10 (@ $0.22/kW-h)


In [98]:
string1 = 'How'
string2 = 'are you my friend'
string3 = 'test'
int1 = 34
int2 = 942885
float1 = -3.0
float2 = 3.141592653589793e-14
print(string1)
print(string1 + ' ' + string2)
print('A. {} {}'.format(string1, string2))
print('B. {0:s} {1:s}'.format(string1, string2))
print('C. {0:s} {0:s} {1:s} - {0:s} {1:s}'.format(string1, string2))
print('D. {0:10s} {1:20s}'.format(string1, string2))
#  print('D. {0:10s} {1:25s} {2:s}'.format(string1, string2, string3))
print(' **')
print(int1, int2)
print('E. {0:d} {1:d}'.format(int1, int2))
print('F. {0:8d} {1:10d}'.format(int1, int2))
print(' ***')
print('G. {0:0.3f}'.format(float1))  # 3 decimal places
print('H. {0:6.3f}'.format(float1))  # 6 decimal places
print('I. {0:8.3f}'.format(float1))  # 8 decimal places
print(2 * 'J. {0:8.3f} '.format(float1))
print(' ****')
print('K. {0:0.3e}'.format(float2))
print('L. {0:12.3e}'.format(float2))
print('L. {0:13.3e}'.format(float2))
print('M. {0:12.3f}'.format(float2))
print(' ****')
print('N. 12345678901234567890')
print('O. {0:s}--{1:8d},{2:10.3e}'.format(string2, int1, float2))

How
How are you my friend
A. How are you my friend
B. How are you my friend
C. How How are you my friend - How are you my friend
D. How        are you my friend   
 **
34 942885
E. 34 942885
F.       34     942885
 ***
G. -3.000
H. -3.000
I.   -3.000
J.   -3.000 J.   -3.000 
 ****
K. 3.142e-14
L.    3.142e-14
L.     3.142e-14
M.        0.000
 ****
N. 12345678901234567890
O. are you my friend--      34, 3.142e-14


In [100]:
a, b, c = "Leon", 47, "March 25"

In [101]:
print(a, "turns", b, "on", c + "th", "this year.")

Leon turns 47 on March 25th this year.


In [102]:
print(f"{a} turns {b} on {c}th this year.")

Leon turns 47 on March 25th this year.


In [110]:
d, t = 149.32, 2.77
print(f"They drove {d:0.1f} miles in {t:0.1f} mph")

They drove 149.3 miles in 2.8 mph


In [106]:
print(f"Their average speed was {d/t:0.1f} mph")

Their average speed was 53.9 mph


#### Printing arrays

In [112]:
import numpy as np

a = np.linspace(3, 19, 7)
a

array([ 3.        ,  5.66666667,  8.33333333, 11.        , 13.66666667,
       16.33333333, 19.        ])

In [114]:
np.set_printoptions(precision=2)
print(a)

[ 3.    5.67  8.33 11.   13.67 16.33 19.  ]


In [115]:
np.set_printoptions(precision=2, floatmode="fixed")

In [116]:
a

array([ 3.00,  5.67,  8.33, 11.00, 13.67, 16.33, 19.00])

In [117]:
print(a)

[ 3.00  5.67  8.33 11.00 13.67 16.33 19.00]


In [119]:
np.set_printoptions(formatter={'float': lambda x: format(x, '5.1e')})
print(a)

[3.0e+00 5.7e+00 8.3e+00 1.1e+01 1.4e+01 1.6e+01 1.9e+01]


In [123]:
np.set_printoptions(formatter={'float': lambda x: format(x, '6.3f')})
print(a)

[ 3.000  5.667  8.333 11.000 13.667 16.333 19.000]


In [124]:
np.set_printoptions(precision=8)
print(a)

[ 3.00000000  5.66666667  8.33333333 11.00000000 13.66666667 16.33333333
 19.00000000]


#### File Input

In [130]:
dataPt, time, height, error = np.loadtxt("mydata.txt", skiprows=5, unpack=True)

In [133]:
np.set_printoptions(formatter={'float': lambda x: format(x, '6.2f')})
time

array([  0.00,   0.50,   1.00,   1.50,   2.00,   2.50,   3.00,   3.50,
         4.00,   4.50,   5.00,   5.50,   6.00])

In [137]:
dataPt, time = np.loadtxt("mydata.txt", skiprows=5, usecols=(0, 1),
                          unpack=True)

In [138]:
dataPt

array([  0.00,   1.00,   2.00,   3.00,   4.00,   5.00,   6.00,   7.00,
         8.00,   9.00,  10.00,  11.00,  12.00])

In [139]:
time

array([  0.00,   0.50,   1.00,   1.50,   2.00,   2.50,   3.00,   3.50,
         4.00,   4.50,   5.00,   5.50,   6.00])

In [141]:
dataPt, time, height, error = np.loadtxt("mydata.csv", skiprows=5, unpack=True,
                                         delimiter=',')

#### Data to a text file

In [5]:
import numpy as np

dataPt, time, height, error = np.loadtxt("mydata.txt", skiprows=5, unpack=True)
np.savetxt("mydataout.txt", list(zip(dataPt, time, height, error)), fmt="%12d %10.2f %12.0f %12.1f")

In [3]:
a = list(zip(dataPt, time, height, error))
a

[(0.0, 0.0, 180.0, 3.5),
 (1.0, 0.5, 182.0, 4.5),
 (2.0, 1.0, 178.0, 4.0),
 (3.0, 1.5, 165.0, 5.5),
 (4.0, 2.0, 160.0, 2.5),
 (5.0, 2.5, 148.0, 3.0),
 (6.0, 3.0, 136.0, 2.5),
 (7.0, 3.5, 120.0, 3.0),
 (8.0, 4.0, 99.0, 4.0),
 (9.0, 4.5, 83.0, 2.5),
 (10.0, 5.0, 55.0, 3.6),
 (11.0, 5.5, 35.0, 1.75),
 (12.0, 6.0, 5.0, 0.75)]

In [6]:
dataPt, time, height, error = np.loadtxt("mydata.txt", skiprows=5, unpack=True)

info = 'Data for falling mass experiment'
info += '\nDate: 04-Aug-2021'
info += '\nData taken by SEB'
info += '\n\n data point time (sec) height (mm)'
info += 'uncertainty (mm)'

np.savetxt('read_write_my_data_header.txt', 
           list(zip(dataPt, time, height, error)),
           header=info, fmt="%12.1f")

In [7]:
np.savetxt('mydataout.csv', list(zip(dataPt, time, height, error)), fmt="%0.1f",
           delimiter=",")