#### Exercises

In [14]:
money = float(input("How mouch money (in dollars) in your lunch account?"))
day = int(input("What day of the month is today?"))
days = int(input("How many days in this month"))
spend = money/(days-day+1)
print(f"You can spend ${spend:0.2f} each day for the rest of the month")

How mouch money (in dollars) in your lunch account? 319
What day of the month is today? 21
How many days in this month 30


You can spend $31.90 each day for the rest of the month


In [16]:
money = float(input("How mouch money (in dollars) in your lunch account?"))
day = int(input("What day of the month is today?"))
month = input("What month is it today?")

months = {"January": 31, "February": 28, "March": 31, "April": 30, "May": 31,
          "June": 30, "July": 31, "August": 31, "September": 30, "October": 31,
          "November": 30, "December": 31}

spend = money/(months[month]-day+1)
print(f"You can spend ${spend:0.2f} each day for the rest of the month")

How mouch money (in dollars) in your lunch account? 319
What day of the month is today? 21
What month is it today? June


You can spend $31.90 each day for the rest of the month


In [1]:
'''Lists and Zips'''
import numpy as np

a = np.array([1, 3, 5, 7])
b = np.array([8, 7, 5, 4])
c = np.array([0, 9, -6, -8])

d = list(zip(a, b, c))
d

[(1, 8, 0), (3, 7, 9), (5, 5, -6), (7, 4, -8)]

In [3]:
print(type(d))
print(type(d[0]))

<class 'list'>
<class 'tuple'>


In [4]:
d[3][2]

-8

In [5]:
g = np.array(d)
g

array([[ 1,  8,  0],
       [ 3,  7,  9],
       [ 5,  5, -6],
       [ 7,  4, -8]])

In [6]:
g[-1, -1]

-8

In [7]:
print(g[1])
print(type(g[1]))

[3 7 9]
<class 'numpy.ndarray'>


In [8]:
'''Read in Data'''

f, a, da = np.loadtxt("LiamSelinaData.txt", skiprows=3, unpack=True)
print(f)
print(a)
print(da)

[ 0.75    1.7885  2.8269  3.8654  4.9038  5.9423  6.9808  8.0192  9.0577
 10.0962 11.1346 12.1731 13.2115 14.25  ]
[13.52 12.11 14.27 16.6  22.91 35.28 60.99 33.38 17.78 10.99  7.47  6.72
  4.4   4.07]
[0.32 0.92 0.73 2.06 1.75 0.91 0.99 0.36 2.32 0.21 0.48 0.51 0.58 0.63]


In [11]:
info = 'Data for exercise 4'
info += '\nDate: 05-January-2025'
info += '\n\n frequency (1/sec) amplitude (mm)'
info += 'uncertainty (mm)'
np.savetxt("my_data_out.txt", list(zip(f, a, da)), header=info, fmt="%12.1f")

In [13]:
np.savetxt('my_data_out.csv', list(zip(f, a, da)), fmt="%0.16e",
           delimiter=",")