In [1]:
import numpy as np


def sphere_area(d: float):
    return np.pi * d ** 2


def sphere_volume(d: float):
    return (np.pi * d ** 3)/6


diameter = []
area = []
volume = []

for i in np.arange(1, 11):
    a = sphere_area(i)
    v = sphere_volume(i)
    diameter.append(i)
    area.append(a)
    volume.append(v)

#np.set_printoptions(formatter={'float': lambda x: format(x, '6.2f')})

diameter = np.array(diameter, dtype=int)
1
area = np.round(np.array(area, dtype=float), decimals=2)
volume = np.round(np.array(volume, dtype=float), decimals=2)

print('diameter' + ' ' + 'area' + ' ' + 'volume')
for i in list(zip(diameter, area, volume)):
    print(i)

print('\ndiameter' + ' ' + 'area' + '      ' + 'volume')
for i in np.arange(0, len(diameter)):
    print(f"{diameter[i]}" + '        ' + f"{area[i]}" + '      ' + f"{volume[i]}")

diameter area volume
(1, 3.14, 0.52)
(2, 12.57, 4.19)
(3, 28.27, 14.14)
(4, 50.27, 33.51)
(5, 78.54, 65.45)
(6, 113.1, 113.1)
(7, 153.94, 179.59)
(8, 201.06, 268.08)
(9, 254.47, 381.7)
(10, 314.16, 523.6)

diameter area      volume
1        3.14      0.52
2        12.57      4.19
3        28.27      14.14
4        50.27      33.51
5        78.54      65.45
6        113.1      113.1
7        153.94      179.59
8        201.06      268.08
9        254.47      381.7
10        314.16      523.6


In [2]:
def price(a, f, cpf=1000, add=12000):
    if f <= 2:
        return a * cpf
    else:
        return a * cpf + add*(f-2)


floor46 = price(46, 1200)
floor5 = price(5, 728)

print(
    f"The total cost of an apartment on the 46th floor "
    f"with a total area of 1200 sq.ft is ${floor46:,}"
)

print(
    f"The total cost of an apartment on the 5th floor "
    f"with a total area of 728 sq.ft is ${floor5:,}"
)

The total cost of an apartment on the 46th floor with a total area of 1200 sq.ft is $14,422,000
The total cost of an apartment on the 5th floor with a total area of 728 sq.ft is $8,717,000


In [3]:
import warnings


def deriv(f, x, h=1.e-9, *params):
    return (f(x + h, *params) - f(x - h, *params)) / (2. * h)


def f0(x):
    return 4 * x**5


def sinc(x):
    warnings.filterwarnings("ignore", category=RuntimeWarning)
    z = np.where(x == 0.0, 1.0, np.sin(x)/x)
    warnings.filterwarnings("always", category=RuntimeWarning)
    return z


deriv(sinc, 2*np.pi)

0.15915495626043438

In [4]:
import numpy as np


def deriv(f, x, h=1.e-9):
    return (f(x + h) - f(x - h)) / (2.0 * h)


def deriv2(f, x, h=1.e-9):
    return (f(x + h) - 2*f(x) + f(x - h)) / (h**2)


def bessel(x, n):
    f = lambda t: np.sin(t)/t  # Importat to keep the variable be callable as a function

    if n == 0:
        return np.where(x == 0.0, 1.0, np.sin(x)/x)

    if n == 1:
        return np.where(x == 0, 0.0, -1*deriv(f, x))

    if n == 2:
        return np.where(x == 0, 0.0, deriv2(f, x))  # This implementation needs correction


for i in range(0, 11):
    print(i, '  ', np.round(bessel(i, 0), decimals=3), '  ',
          np.round(bessel(i, 1), decimals=3), '  ', np.round(bessel(i, 2), decimals=3))

0    1.0    0.0    0.0
1    0.841    0.301    0.0
2    0.455    0.435    0.0
3    0.047    0.346    6.939
4    -0.189    0.116    -27.756
5    -0.192    -0.095    27.756
6    -0.047    -0.168    13.878
7    0.094    -0.094    13.878
8    0.124    0.034    0.0
9    0.046    0.106    0.0
10    -0.054    0.078    -6.939


/var/folders/78/hgt6ztdn5bvbxpk7fmt5jlfc0000gn/T/ipykernel_722/3444985951.py:16: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(x == 0.0, 1.0, np.sin(x)/x)
/var/folders/78/hgt6ztdn5bvbxpk7fmt5jlfc0000gn/T/ipykernel_722/3444985951.py:13: RuntimeWarning: invalid value encountered in scalar divide
  f = lambda t: np.sin(t)/t  # Importat to keep the variable be callable as a function


In [18]:
import random

x = random.randint(1, 6)
x

6

In [42]:
import random


def dice(n):
    dice = []
    for i in range(1, n + 1):
        n = random.randint(1, 6)
        dice.append(n)
    print(dice)
    return np.array(dice).sum()


for i in range(2, 6):
    print("number of dice =", i)
    for j in range(1, 4):
        a = dice(i)
        print(a)

number of dice = 2
[1, 1]
2
[6, 2]
8
[1, 1]
2
number of dice = 3
[6, 6, 5]
17
[4, 3, 4]
11
[5, 3, 6]
14
number of dice = 4
[2, 5, 4, 1]
12
[1, 4, 6, 1]
12
[6, 1, 4, 4]
15
number of dice = 5
[4, 4, 4, 1, 4]
17
[6, 1, 3, 1, 2]
13
[1, 5, 3, 6, 6]
21


In [38]:
dice(7)

[5, 2, 5, 5, 1, 2, 5]


25

In [42]:
import numpy as np


def line(x, a, b):
    '''Line function'''
    return a + b*x


def linefit(x, y):
    '''Returns the slope and y-intercept of linear fit to (x, y) data set'''
    xavg = x.mean()
    slope = (y * (x - xavg)).sum() / (x * (x - xavg)).sum()
    yint = y.mean() - slope * xavg
    return yint, slope


def linefitWt(x, y, dy):
    '''Linear regression with Weighting'''
    xbar = ((x/dy**2).sum())/((1/dy*2).sum())
    ybar = ((y/dy**2).sum())/((1/dy*2).sum())

    b = ((x - xbar) * (y/dy**2)).sum()/((x - xbar) * (x/dy**2)).sum()
    a = ybar - b*xbar
    return a, b


def chir(x, y, dy, a, b):
    '''Chi value definition'''
    chi = (((y - a - b*x)/dy)**2).sum()
    return chi/(len(x)-2)


def chir2(f, x, y, dy, *params):  # Revisar las implicaciones teóricas
    model = f(x, *params)
    chi = (((y - model)/dy)**2).sum()
    return chi/(len(y) - 2)


t, y, dy = np.loadtxt('mydata.txt', skiprows=2, unpack=True)
chir(t, y, dy, *linefitWt(t, y, dy))


chir2(line, t, y, dy, *linefitWt(t, y, dy))

110.4246391136383

In [24]:
linefit(t, y)

(171.89273556960842, -9.23414248039144)

In [26]:
linefitWt(t, y, dy)

1.1783131982490707

In [29]:
t/(dy**2)

array([0.00871094, 0.01867188, 0.450625  , 0.11567901, 0.04027682,
       0.04923875, 0.11493056, 0.08311111, 0.06496914, 0.2321    ])

In [30]:
t/dy**2

array([0.00871094, 0.01867188, 0.450625  , 0.11567901, 0.04027682,
       0.04923875, 0.11493056, 0.08311111, 0.06496914, 0.2321    ])

In [31]:
1/dy

array([0.0625    , 0.0625    , 0.25      , 0.11111111, 0.05882353,
       0.05882353, 0.08333333, 0.06666667, 0.05555556, 0.1       ])

In [33]:
ybar = ((y/dy**2).sum())/((1/dy*2).sum())
ybar

5.093673483020042

In [17]:
import math
import numpy as np


def derivA(f, x, h=1.e-9, *params):  # Tuple
    return (f(x + h, *params) - f(x - h, *params)) / (2.*h)


def derivK(f, x, h=1.e-9, **params):  # Dictionary
    return (f(x + h, **params) - f(x - h, **params)) / (2.*h)


def p(x, a, b, c):
    return a + b * x + c * x**2


def V(t, V0, R, C):
    return V0*(1 - np.e ** (-t/(R*C)))


print(derivA(p, -3, 1.e-9, *(2.1, -3.2, 5.8)))
print(derivK(p, -3, 1.e-9, **{'a': 2.1, 'b': -3.2, 'c': 5.8}))

-38.0000031441341
-38.0000031441341


In [22]:
t = np.array([0., 0.2, 0.4, 0.6, 0.8, 1.])

print(derivA(V, t, 1.e-9, *(5., 100000, 1.e-6)))
print(derivK(V, t, 1.e-9, **{'V0': 5., 'R': 100000, 'C': 1.e-6}))

[4.99999997e+01 6.76676448e+00 9.15782117e-01 1.23937305e-01
 1.67732495e-02 2.26973995e-03]
[4.99999997e+01 6.76676448e+00 9.15782117e-01 1.23937305e-01
 1.67732495e-02 2.26973995e-03]


In [10]:
import math


print(math.e)

2.718281828459045


In [14]:
np.e ** 2

7.3890560989306495

In [20]:
import numpy as np


def square(a, c, p):
    '''Function to integrate'''
    return c*a**p


def sine(a, A, k):
    '''Sin function'''
    return A*np.sin(a*k)


def trapezoid2(f, a, b, tol=1.0e-8, **fparams):
    '''Trapezoid rule 2'''
    h0 = b-a
    A0 = 0.5*(b-a)*(f(a, **fparams) + f(b, **fparams))
    AT = A0

    for n in range(1, 10):
        print(f"Value of n is {n}")
        print(f"Área anterior es {AT}")
        Aa = AT
        AT *= 0.5
        print(f"Área anterior dividida en dos es {AT}\n")
        h0 *= 0.5
        print(f"Nuevo valor de h0 es {h0}")
        s = 0
        print(f"Value of h0 is {h0}")
        for i in range(1, 2**n + 1, 2):
            print(f"Value of i is {i}")
            s += h0*(f(a + i*h0, **fparams))
            #A = 0.5*A0 + h0*0.5*(f(a + h0*0.5, **fparams))
        print(f"Área anterior dividida en dos es {AT}")
        print(f"Sumatoria es {s}")
        AT = AT + s
        Ad = AT
        print(f"Presition is: {np.abs((Ad-Aa)/Ad)}")
        print(f"El área es {AT}\n")

        if np.abs((Ad-Aa)/Ad) < tol:
            break

    return AT


#print(trapezoid2(square, 1, 5, tol=1.0e-8, **{'c': 2, 'p': 3}))  # Test of trapezoid rule
print(trapezoid2(square, 2, 5, tol=1.0e-8, **{'c': 1, 'p': 2}))  # Review precision

Value of n is 1
Área anterior es 43.5
Área anterior dividida en dos es 21.75

Nuevo valor de h0 es 1.5
Value of h0 is 1.5
Value of i is 1
Área anterior dividida en dos es 21.75
Sumatoria es 18.375
Presition is: 0.08411214953271028
El área es 40.125

Value of n is 2
Área anterior es 40.125
Área anterior dividida en dos es 20.0625

Nuevo valor de h0 es 0.75
Value of h0 is 0.75
Value of i is 1
Value of i is 3
Área anterior dividida en dos es 20.0625
Sumatoria es 19.21875
Presition is: 0.021479713603818614
El área es 39.28125

Value of n is 3
Área anterior es 39.28125
Área anterior dividida en dos es 19.640625

Nuevo valor de h0 es 0.375
Value of h0 is 0.375
Value of i is 1
Value of i is 3
Value of i is 5
Value of i is 7
Área anterior dividida en dos es 19.640625
Sumatoria es 19.4296875
Presition is: 0.005398920215956809
El área es 39.0703125

Value of n is 4
Área anterior es 39.0703125
Área anterior dividida en dos es 19.53515625

Nuevo valor de h0 es 0.1875
Value of h0 is 0.1875
Value of

In [26]:
trapezoid1(square, 2, 5, tol=1.0e-8, **{'c': 1, 'p': 2})

43.5

In [38]:
0.5*43.5 + 1.5*(3.5**2)

40.125

In [35]:
0.5*43.5

21.75

In [36]:
1.5*(3.5**2)

18.375

In [116]:
0.5*40.125 + (3*0.5*0.5)*((2 + 3*0.5*0.5)**2)

25.734375

In [ ]:
print(trapezoid2(square, 2, 5, tol=1.0e-8, **{'c': 1, 'p': 2}))  # Review precision


In [21]:
print(trapezoid2(sine, 0, np.pi, tol=1.0e-8, **{'A': 1, 'k': 1}))  # Review precision

Value of n is 1
Área anterior es 1.9236706937217898e-16
Área anterior dividida en dos es 9.618353468608949e-17

Nuevo valor de h0 es 1.5707963267948966
Value of h0 is 1.5707963267948966
Value of i is 1
Área anterior dividida en dos es 9.618353468608949e-17
Sumatoria es 1.5707963267948966
Presition is: 0.9999999999999999
El área es 1.5707963267948966

Value of n is 2
Área anterior es 1.5707963267948966
Área anterior dividida en dos es 0.7853981633974483

Nuevo valor de h0 es 0.7853981633974483
Value of h0 is 0.7853981633974483
Value of i is 1
Value of i is 3
Área anterior dividida en dos es 0.7853981633974483
Sumatoria es 1.1107207345395915
Presition is: 0.1715728752538099
El área es 1.8961188979370398

Value of n is 3
Área anterior es 1.8961188979370398
Área anterior dividida en dos es 0.9480594489685199

Nuevo valor de h0 es 0.39269908169872414
Value of h0 is 0.39269908169872414
Value of i is 1
Value of i is 3
Value of i is 5
Value of i is 7
Área anterior dividida en dos es 0.94805944